services:
  - type: web
    name: linklock-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start --workspace=@link-lock/api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  - type: pserv
    name: linklock-db
    plan: free
    ipAllowList: []
